### PR TITLE
WIP: New version with single autocomplete and Storybook

### PR DESCRIPTION
**Pull request by it-nalon**
### Description
New Version (WIP) that introduce single item autocomplete (#2, #4, #26) and replace the example project with Storybook.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Todo:
- [x] Add Storybook
- [x] Single item Autocomplete input
- [ ] Fix components structure
- [ ] Remove `/example` project
- [ ] Write documentation
- [ ] Write Tests
- [ ] Write example stories

### CODE REVIEW

**Comment by koolamusic** [comment]
Thanks for making this PR. going to work through the checklist and see how much we can cover.

**Comment by adamint** [comment]
Is there a status update on this? @koolamusic

**Comment by koolamusic** [comment]
@adamint been caught up with work for a while, rest assured once I am able to clear out my place this week, I will take a look at this over the weekend

**Comment by koolamusic** [comment]
@all-contributors please add @it-nalon for tests and code

**Comment by lukeeey** [comment]
@koolamusic

**Pull request closed without merging**
