### PR TITLE
Add CodeSandbox links to README

### PR DESCRIPTION
**Pull request by vyder**
It's nice to be able to play around with a live example - so I made one using the example jsx code. Figured I would share back to the repo.

### CODE REVIEW

**Comment by koolamusic** [comment]
Thanks a lot for this, much appreciated.

**Comment by koolamusic** [comment]
Screenshot_2021-02-26 CodeSandbox
Just as an enhancement, could you consider attaching this image to the link

**Comment by vyder** [comment]
Sure, you mean like this?

Screen Shot 2021-03-01 at 3 11 25 PM

I moved the link below the code

**Comment by vyder** [comment]
I can squash the commits once you okay, if you like

**Comment by koolamusic** [comment]
Totally fine. looks good to me

**Pull request merged**
